server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8083
  servlet:
    context-path: /generator

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sixeco_acgn
    username: dev
    password: dev123456
#    url: jdbc:mysql://rm-uf60841xu50evrh921o.mysql.rds.aliyuncs.com:3306/redt-3.0?rewriteBatchedStatements=true&characterEncoding=UTF8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull
#    username: xpower_dev
#    password: Xpower@123
#    url: jdbc:mysql://124.71.181.176:3306/sixeco-user-assets?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: dev
#    password: dev123456



  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
renren:
  database: mysql

